version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: smart-keyword-extractor
    ports:
      - "8006:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
